PULP_APP = hyperbus_udma
PULP_APP_FC_SRCS = hyperbus_udma.c
PULP_APP_HOST_SRCS = hyperbus_udma.c
PULP_CFLAGS = -O3 -g
vsim_additional_flags=-gUSE_PSRAM_MODEL=1

include $(PULP_SDK_HOME)/install/rules/pulp_rt.mk
